project:
  type: website
  output-dir: docs

website:
  title: "jkunze"
  navbar:
    left:
      - href: index.qmd
        text: Home
#      - about.qmd

format:
  html:
    theme: zephyr
    css: styles.css
#    toc: true

